# Generated by Django 3.1.2 on 2020-11-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('employee_view', 'Global Employee View'), ('supervisor_view', 'Global supervisor view'), ('management_view', 'Global management view'))},
        ),
    ]
