# Generated by Django 3.1.2 on 2020-11-16 00:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='timeKeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeType', models.TextField(choices=[('Paid Time Off', 'Paid Time Off'), ('Sick Time', 'Sick Day'), ('Overtime', 'Overtime'), ('Standard Time', 'Standardtime')], default='Standard Time')),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('lunchin_time', models.DateTimeField(blank=True, null=True)),
                ('lunchout_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('clocked_in', models.BooleanField(default=False)),
                ('currentDate', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='timekeep',
            constraint=models.UniqueConstraint(fields=('user', 'currentDate'), name='unique user date'),
        ),
    ]
