# Generated by Django 3.1.2 on 2020-11-29 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='dateTimeEntered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timekeep',
            name='timeType',
            field=models.TextField(choices=[('Paid Time Off', 'Paid Time Off'), ('Sick Time', 'Sick Day'), ('Overtime', 'Overtime'), ('Standard Time', 'Standardtime')], default='Standard Time'),
        ),
        migrations.AddConstraint(
            model_name='timekeep',
            constraint=models.UniqueConstraint(fields=('user', 'dateTimeEntered'), name='unique user date'),
        ),
    ]
