# Generated by Django 3.1.2 on 2020-11-19 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='is_Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timekeep',
            name='currentDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
