# Generated by Django 3.1.2 on 2020-11-16 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='currentDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='timekeep',
            constraint=models.UniqueConstraint(fields=('user', 'currentDate'), name='unique user date'),
        ),
    ]
