# Generated by Django 3.1.2 on 2020-11-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='currentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
