# Generated by Django 3.1.2 on 2020-11-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20201129_1450'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timekeep',
            name='unique user date',
        ),
    ]
