# Generated by Django 3.1.2 on 2020-10-19 21:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('times', '0002_auto_20201014_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 16, 33, 18, 632451)),
        ),
        migrations.AlterField(
            model_name='time',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
