# Generated by Django 3.1.2 on 2020-11-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20201119_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timekeep',
            name='is_Manual',
        ),
    ]
