# Generated by Django 3.1.2 on 2020-10-27 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('times', '0002_auto_20201014_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeKeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lunch_timein', models.DateTimeField(blank=True, null=True)),
                ('lunch_timeout', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('clocked_in', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='time',
        ),
    ]
