# Generated by Django 3.1.2 on 2020-11-18 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20201115_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='timeType',
            field=models.TextField(choices=[('Paid Time Off', 'Paid Time Off'), ('Sick Time', 'Sick Day'), ('Overtime', 'Overtime'), ('Standard Time', 'Standardtime')], default='Standard Time'),
        ),
        migrations.AlterField(
            model_name='timekeep',
            name='currentDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
