# Generated by Django 3.1.2 on 2020-12-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20201129_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='is_Manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timekeep',
            name='dateTimeEntered',
            field=models.DateField(default=None, null=True),
        ),
    ]
