# Generated by Django 3.1.2 on 2020-10-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20201026_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeep',
            name='in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
