# Generated by Django 3.1.2 on 2020-12-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_auto_20201202_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeep',
            name='timeType',
            field=models.TextField(choices=[('Paid Time Off', 'Paid Time Off'), ('Sick Day', 'Sick Day'), ('Overtime', 'Overtime'), ('Standard Time', 'Standardtime')], default='Standard Time'),
        ),
    ]
