# Generated by Django 3.1.2 on 2020-10-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_auto_20201027_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeep',
            name='clocked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timekeep',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
