# Generated by Django 3.1.2 on 2020-10-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_auto_20201028_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timekeep',
            name='clocked_in',
        ),
        migrations.RemoveField(
            model_name='timekeep',
            name='lunch_timein',
        ),
        migrations.RemoveField(
            model_name='timekeep',
            name='lunch_timeout',
        ),
        migrations.RemoveField(
            model_name='timekeep',
            name='out_time',
        ),
    ]
