# Generated by Django 3.1.2 on 2020-12-15 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_auto_20201203_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeep',
            name='dateTimeEntered',
            field=models.DateField(default=datetime.datetime(2020, 12, 14, 23, 24, 1, 881473, tzinfo=utc), null=True),
        ),
    ]
