# Generated by Django 3.1.2 on 2020-11-03 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0008_auto_20201029_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeep',
            name='clocked_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timekeep',
            name='lunchin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timekeep',
            name='lunchout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timekeep',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timekeep',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 23, 5, 33, 128331, tzinfo=utc)),
        ),
    ]
