# Generated by Django 3.1.2 on 2020-11-04 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0009_auto_20201103_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeep',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 22, 43, 23, 753096, tzinfo=utc)),
        ),
    ]
