# Generated by Django 3.1.2 on 2020-11-05 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0010_auto_20201104_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeep',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
