# Generated by Django 3.1.2 on 2020-10-19 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattrib',
            name='PTO_Acc_Rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userattrib',
            name='Sick_Acc_Rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='PTO',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='Sick_Time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userattrib',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
