# Generated by Django 3.1.2 on 2020-11-03 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_Type', models.TextField(choices=[('Paid Time Off Request', 'Paid Time Off'), ('Sick Day Request', 'Sick Day'), ('Overtime Request', 'Overtime'), ('Time Correction Request', 'Time Correction')], default='Paid Time Off Request')),
                ('start_Date', models.DateField(default=None)),
                ('end_Date', models.DateField(default=None)),
                ('start_Time', models.TimeField(default=None)),
                ('end_Time', models.TimeField(default=None)),
                ('status', models.TextField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Requested')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
