# Generated by Django 3.1.2 on 2020-11-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201102_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PTO_Accrual_Rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='PTO_Hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Sick_Accrual_Rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Sick_Hours',
            field=models.FloatField(default=0),
        ),
    ]
