# Generated by Django 3.1.2 on 2020-10-19 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20201019_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userAttrib',
            new_name='userAttributes',
        ),
        migrations.RenameField(
            model_name='userattributes',
            old_name='PTO',
            new_name='PTO_Accrual_Rate',
        ),
        migrations.RenameField(
            model_name='userattributes',
            old_name='PTO_Acc_Rate',
            new_name='PTO_Hours',
        ),
        migrations.RenameField(
            model_name='userattributes',
            old_name='Sick_Acc_Rate',
            new_name='Sick_Accrual_Rate',
        ),
        migrations.RenameField(
            model_name='userattributes',
            old_name='Sick_Time',
            new_name='Sick_Hours',
        ),
    ]
