# Generated by Django 3.1.2 on 2020-10-19 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20201019_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userAttributes',
            new_name='userAttribute',
        ),
    ]
