# Generated by Django 3.1.2 on 2020-11-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201102_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='end_Date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='end_Time',
        ),
        migrations.RemoveField(
            model_name='request',
            name='start_Date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='start_Time',
        ),
        migrations.AddField(
            model_name='request',
            name='end_Date_Time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='start_Date_Time',
            field=models.DateTimeField(default=None),
        ),
    ]
