# Generated by Django 3.1.2 on 2020-11-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201114_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PTO_Hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sick_Hours',
            field=models.FloatField(default=0),
        ),
    ]
