# Generated by Django 3.1.2 on 2020-11-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201114_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='end_Date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='end_Time',
        ),
        migrations.RemoveField(
            model_name='request',
            name='start_Date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='start_Time',
        ),
        migrations.AddField(
            model_name='request',
            name='end_Date_Time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='start_Date_Time',
            field=models.DateTimeField(default=None),
        ),
    ]
