# Generated by Django 3.1.2 on 2020-10-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201019_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattribute',
            old_name='user',
            new_name='username',
        ),
    ]
