# Generated by Django 3.1.2 on 2020-10-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201023_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattribute',
            old_name='username',
            new_name='user',
        ),
    ]
