# Generated by Django 3.1.2 on 2020-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201114_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PTO_Hours',
            field=models.FloatField(default=0, max_length=200),
        ),
    ]
