# Generated by Django 3.1.2 on 2020-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201117_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PTO_Hours',
            field=models.IntegerField(default=0),
        ),
    ]
