# Generated by Django 3.1.2 on 2020-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201117_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PTO_Accrual_Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sick_Accrual_Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sick_Hours',
            field=models.IntegerField(default=0),
        ),
    ]
