# Generated by Django 3.1.2 on 2020-10-27 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_auto_20201023_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.TextField(choices=[('Paid Time Off Request', 'Paid Time Off'), ('Sick Day Request', 'Sick Day'), ('Overtime Request', 'Overtime'), ('Time Correction Request', 'Time Correction')], default='Paid Time Off Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
