# Generated by Django 3.1.2 on 2020-10-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201027_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_type',
            new_name='Request_Type',
        ),
    ]
