# Generated by Django 3.1.2 on 2020-11-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201117_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PTO_Accrual_Rate',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sick_Accrual_Rate',
            field=models.FloatField(default=0, max_length=3),
        ),
    ]
