# Generated by Django 3.1.2 on 2020-10-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201027_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Request_Type',
            new_name='request_Type',
        ),
    ]
