# Generated by Django 3.1.2 on 2020-10-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20201027_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='end_Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='end_Time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='start_Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='start_Time',
            field=models.TimeField(default=None),
        ),
    ]
