# Generated by Django 3.1.2 on 2020-10-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201028_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='Requested', max_length=30),
        ),
    ]
