# Generated by Django 3.1.2 on 2020-12-08 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20201202_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PTO_Accrual_Rate',
            field=models.FloatField(default=0, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sick_Accrual_Rate',
            field=models.FloatField(default=0, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
