# Generated by Django 3.1.2 on 2020-12-10 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201207_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='submission_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 10, 2, 48, 5, 465090, tzinfo=utc)),
        ),
    ]
