# Generated by Django 3.1.2 on 2020-12-15 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_request_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='submission_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 5, 24, 1, 882470, tzinfo=utc)),
        ),
    ]
